name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'violet/**'
      - '.github/workflows/build_apk.yml'

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'
          cache: true

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,x86_64-linux-android,i686-linux-android

      - name: Install Cargo NDK
        run: cargo install cargo-ndk

      - name: Install Dependencies
        working-directory: violet
        run: flutter pub get

      - name: Build APK (Release)
        working-directory: violet
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: violet-apk-release
          path: violet/build/app/outputs/flutter-apk/app-release.apk